const body = document.querySelector('body');
const scaffold = document.createElement('div');
scaffold.className = 'scaffold-container';
const svg = document.createElement('div');
svg.className = 'svg-el';
const hero = document.createElement('h1');
hero.className = 'hero-el';
hero.innerText = 'Hangman game'.toUpperCase();
scaffold.append(svg, hero);
const main = document.createElement('div');
main.className = 'main-container';
const answer = document.createElement('h2');
answer.className = 'answer-el';
const question = document.createElement('p');
question.className = 'question-el';
const guesses = document.createElement('p');
guesses.className = 'guesses-el';
const keyboard = document.createElement('div');
keyboard.className = 'keyboard-el';
main.append(answer, question, guesses, keyboard);
body.append(scaffold, main);
